version: "3"
name: meside-prod

services:
  db:
    image: postgres:15
    container_name: meside-db-prod
    command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
    restart: always
    environment:
      POSTGRES_USER: meside
      POSTGRES_PASSWORD: meside
      POSTGRES_DB: meside
    volumes:
      - ./prod/volumes/db/data:/var/lib/postgresql/data
    networks:
      - meside-network

  redis:
    image: redis:latest
    container_name: meside-redis-prod
    restart: always
    volumes:
      - ./prod/volumes/redis/data:/data
    networks:
      - meside-network

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: meside-jaeger-prod
    environment:
      - LOG_LEVEL=debug
    networks:
      - meside-network

  server:
    image: meside/server:latest
    container_name: meside-server-prod
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://meside:meside@db:5432/meside
      - REDIS_URL=redis://redis:6379
      - JAEGER_URL=http://jaeger:16686
      - OTLP_TRACE_EXPORTER_URL=http://jaeger:4318/v1/traces
    networks:
      - meside-network

  warehouse:
    image: meside/warehouse:latest
    container_name: meside-warehouse-prod
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://meside:meside@db:5432/meside
      - REDIS_URL=redis://redis:6379
      - SERVER_DOMAIN=http://server:3000/
      - ASSET_PREFIX=http://warehouse:3000/
    networks:
      - meside-network

  web:
    image: meside/web:latest
    container_name: meside-web-prod
    restart: always
    depends_on:
      - server
      - warehouse
    networks:
      - meside-network
    environment:
      - SERVER_DOMAIN=http://server:3000/
    ports:
      - "80:3000"

networks:
  meside-network:
    driver: bridge
