name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check Types
        run: bun run check-types

      - name: Check
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract metadata for warehouse Docker image
        id: meta-warehouse
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/warehouse

      - name: Build warehouse Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/warehouse
          file: ./apps/warehouse/Dockerfile
          push: true
          tags: ${{ steps.meta-warehouse.outputs.tags }}
          labels: ${{ steps.meta-warehouse.outputs.labels }}

      - name: Extract metadata for server Docker image
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/server

      - name: Build server Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/server
          file: ./apps/server/Dockerfile
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}

      - name: Extract metadata for web Docker image
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/web

      - name: Build web Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
